dist: xenial
language: python
python:
  - "3.6"
services: 
  - mysql
env: 
  -DJANGO=2.1 DB=mysql
install:
  - 'pip install pipenv'
  - 'pipenv install'
before_script:
  - mysql -e 'create database pj2;' -u root
script: 
  - python src/manage.py test
branches:
  only:
    - develop
