dist: xenial
language: python
python:
  - "3.6"
services: 
  - mysql
env: 
  -DJANGO=2.1 DB=mysql
install:
  - 'pip install pipenv'
  - 'pipenv install'
before_script:
- mysql -u root -e 'CREATE DATABASE pj2;'
- mysql -u root -e "CREATE USER 'pj2'@'localhost' IDENTIFIED BY '123';"
- mysql -u root -e "GRANT ALL ON pj2.* TO 'pj2'@'localhost';"
- mysql -u root -e "GRANT ALL ON test_pj2.* TO 'pj2'@'localhost';"
script: 
  - cd src
  - python manage.py test
branches:
  only:
    - develop
