# Generated by Django 2.1.7 on 2019-02-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_c_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_at',
        ),
    ]
